# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb06596634861e3cdd7f27baddbc9f5a669f3ec5d305ecbd2bc882e9fb400f2bcf295318fed8ba950608229a9fc564565c9fa7cb7d20e71580f6e530fb6ae4a

test:
  secret_key_base: f2bdc9e391da0ca458ca03e08ce6041f4f1e6c511cb7600c3e03228cce597cb5396335d240bbba6eb42dfe8c2fef1b78da611ea2e0b98558105a2321c75a572d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
